# -*- coding: utf-8 -*-
"""06-30 Baekjoon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pccyhhNuGfj7s_gViYGOypIizkCB1Zm6
"""

a_list = []
for i in range(10):
  a = int(input())
  if a%42 not in a_list:
    a_list.append(a%42)
a_list