# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1blJwjMOYopJjLcnb7ASEajUv-6w0hDdX

#10039 평균점수
"""

score = 0
for i in range(5):
  s = int(input())
  if s <40:
    s=40
  score += s
print(score/5)