# -*- coding: utf-8 -*-
"""07-19 BaekJoon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eyiDi3Q4HtrNTK-ldgD9k4X0jGMnYvNx

#### #5554 심부름 가는 길
https://www.acmicpc.net/problem/5554
"""

total = 0
for i in range(4):
  a = int(input())
  total += a
print(total//60, total%60, sep='\n')

"""#### #10950 A + B - 3
https://www.acmicpc.net/problem/10950
"""

T = int(input())
for i in range(T):
  a, b = map(int, input().split())
  print(a+b)