# -*- coding: utf-8 -*-
"""07-20 BaekJoon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R72walDT3-Eux1_0M7ckayoK5feS0Osx

#25304 영수증
"""

X = int(input())
N = int(input())
total=0
for i in range(N):
  a, b = map(int, input().split())
  total += (a*b)

if total == X:
  print('Yes')
else:
  print('No')

"""#11021 A+B"""

T = int(input())
for i in range(T):
  A, B = map(int, input().split())
  print("Case #%s: %d" %(i+1, A+B))

"""# 11022 A+B"""

T = int(input())
for i in range(T):
  A, B = map(int, input().split())
  print("Case #" + str(i+1) + ":", A, "+", B, "=", A+B)

"""#10952 A+B"""

while True:
  A, B = map(int, input().split())
  if (A==0 and B==0):
    break
  else:
    print(A+B)

"""#10951 A+B"""

while True:
  try:
    A, B = map(int, input().split())
    print(A+B)
  except:
    break