# -*- coding: utf-8 -*-
"""07-21 BaekJoon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R72walDT3-Eux1_0M7ckayoK5feS0Osx

#11720 숫자의 합
"""

N = int(input())
print(sum(map(int, input())))

"""#11718 그대로 출력하기"""

while True:
  try:
    a = input()
    print(a)
  except:
    break

"""#2420 사파리월드"""

a, b = map(int, input().split())
print(abs(a-b))